# Run in context .. (base directory)
FROM node:10-alpine
ADD . /code
WORKDIR /code
RUN yarn install
WORKDIR /code/client
RUN yarn run build

FROM nginx:latest
WORKDIR /usr/share/nginx/html
COPY --from=0 /code/client/dist/* ./
