version: "3"
services:
  db:
    image: "mongo:4"

  api:
    build:
      context: "."
      dockerfile: "./api/Dockerfile"
    environment:
      MONGO_URI: "mongodb://db:27017"
    ports:
      - "3000:3000"

  client:
    build:
      context: "."
      dockerfile: "./client/Dockerfile"
    ports:
      - "4000:80"
