version: "3.2"
services:
  db:
    image: "mongo:4"

  api:
    build:
      context: "."
      dockerfile: "./api/Dockerfile"
    volumes:
      - type: bind
        source: "."
        target: "/code"
    environment:
      MONGO_URI: "mongodb://db:27017"
    ports:
      - "3000:3000"

  client:
    build:
      context: "."
      dockerfile: "./client/Dockerfile"
    volumes:
      - type: bind
        source: "."
        target: "/code"
    ports:
      - "8080:8080"
